### ISSUE TITLE
Saved games bug

### ISSUE THREAD

**Issue by annihat** [SecUSo/privacy-friendly-minesweeper#12]
My saved games tab contains many games which are devoid of mines.

**Comment by annihat** [comment]
When displayed, the field is initially dark tiles but within a second clears to a blank field. The game then saves with the current date & time.

These blank games cannot be deleted.

**Comment by jackastner** [comment]
I think this is the same as issue #4. If you want a work around and don't mind installing from source, you can checkout pull request #9 where I added a button to delete saved games.

**Comment by annihat** [comment]
Whilst I can recreate #4 I'm not yet convinced it's the same issue. If I spot what's going on I'll update here. 

Sorry, I can't yet compile from source. (I've installed Termux in an attempt to solve a different problem so it's theoretically possible but I have no idea how to do it. Android is nothing like MSDOS or Windows-3 where I could do this)
