### ISSUE TITLE
Problem continuing unstarted games

### ISSUE THREAD

**Issue by sandersrc** [SecUSo/privacy-friendly-minesweeper#14]
Description of problem
-Create a new game. 
-Don't activate anything on new game board. 
-Exit to menu. 
-Select continue game. 
-Continue the game you created but didn't start. 
-All tiles turn lite blue and nothing can be selected. 
-This game will be stuck in your continue games menu indefinitely. 

Thank you
Ryan

![Screenshot_20220210-153057](https://user-images.githubusercontent.com/47764437/153492789-b7d001d3-325b-44dc-bdcb-04312541aae1.png)

![Screenshot_20220210-153053](https://user-images.githubusercontent.com/47764437/153492808-136d58bb-3479-4793-ac71-baed02c0c20d.png)

**Comment by bengan** [comment]
I've got the same problem. Nexy problem. The app seems abandoned.
