### ISSUE TITLE
Sometimes tapping on a square reveals all tiles and all are blank

### ISSUE THREAD

**Issue by mpnordland** [SecUSo/privacy-friendly-minesweeper#4]
Sometime it seems as if the game is generated without mines, and the first tap reveals the whole board. It has happened twice on easy and once on medium. After that, there is no way to win the game or remove it from saved games.

Run on Huawei Mate 9

**Comment by z4zen** [comment]
The bug can be reproduced with these steps:
1. Start a new game (any difficulty)
2. Switch to any other application / home screen before marking or opening the first blue box of the game (this will save the game)
3. Switch back to the game and resume the game (progress bar shows 0%)
4. Click any blue box (the game will fill all boxes as revealed)
5. Now this game cannot be completed or deleted anymore (progress bar shows 100%)

**Comment by petermayer** [comment]
Thanks for the steps to reproduce this issue @z4zen! I could reproduce it on two different devices.

**Comment by alfalfascout** [comment]
Interesting to note: if you find that you've accidentally quit out of a game before revealing any tiles, you can avert the permanent uncompletable savegame by following these steps.

1. Continue the game in question
2. Enter 'mark mines' mode
3. Mark squares as mines until the count drops to 0
4. Leave 'mark mines' mode
5. Tap any unmarked square to 'solve' the puzzle. 

If you have already saved the game with all the tiles revealed, it is too late to use this method.
